name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  REGION: asia-southeast2 
  PROJECT_ID: silver-treat-443814-v3
  SERVICE_NAME: ssd-test

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    environment: env

    steps:
      - uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Build and Push Container
        run: |
          docker build -t asia-southeast2-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push asia-southeast2-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image asia-southeast2-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --add-cloudsql-instances=${{ env.PROJECT_ID }}:${{ env.REGION }}:ssd-test-db \
            --update-env-vars="APP_KEY=${{ secrets.APP_KEY }}" \
            --update-env-vars="APP_DEBUG=${{ secrets.APP_DEBUG }}" \
            --update-env-vars="DB_CONNECTION=${{ secrets.DB_CONNECTION }}" \
            --update-env-vars="DB_HOST=${{ secrets.DB_HOST }}" \
            --update-env-vars="DB_PORT=${{ secrets.DB_PORT }}" \
            --update-env-vars="DB_DATABASE=${{ secrets.DB_DATABASE }}" \
            --update-env-vars="DB_USERNAME=${{ secrets.DB_USERNAME }}" \
            --update-env-vars="DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
            --update-env-vars="PROJECT_ID=${{ env.PROJECT_ID }}" \
            --update-env-vars="REGION=${{ env.REGION }}" \
            --project ${{ env.PROJECT_ID }}
